version: '3'
services:
  nestjs:
    image: sanhotel-ranking/backend:beta
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-ranking
    restart: on-failure
    ports:
      - "8001:8001"
    depends_on:
      - postgres-db
    command: bash -c "./wait-for-it.sh -t 600 postgres-db:5432 && npm run start:prod"
    volumes:
      - .:/app
      - /app/node_modules
  # chrome:
  #   image: selenium/node-chrome:beta
  #   container_name: chrome-ranking
  #   shm_size: 2gb
  #   restart: always
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    build:
      context: .
      dockerfile: Dockerfile.firefox
    image: selenium/node-firefox:beta
    container_name: firefox-ranking
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  selenium-hub:
    image: selenium/hub:latest
    restart: always
    container_name: selenium-hub-ranking
    ports:
      - "4445:4442"
      - "4446:4443"
      - "4447:4444"
  postgres-db:
    image: postgres:12
    container_name: postgres_ranking
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    command: postgres -c 'max_connections=1000'
    env_file:
      - .env
    # expose:
    #   - '5433'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_ranking
    restart: always
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: buituan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:
  postgres:
    name: crawl-db-ranking
